version: '3.7'

services:
  frontend-dev:
    profiles: ["dev"]
    restart: always
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - "./frontend:/frontend/app"
      - "/app/node_modules"
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: 'backend/'
      dockerfile: 'Dockerfile'
    restart: 'always'
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 5432:5432
    environment:
      PORT: 5432
    volumes:
      - '$PWD/backend:/backend'
